-- AlterTable
ALTER TABLE "event" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "body" DROP NOT NULL,
ALTER COLUMN "start" SET DATA TYPE DATE,
ALTER COLUMN "end" SET DATA TYPE DATE,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "color" DROP NOT NULL;
